name: actionsDemo

#Events - When some something happens to the master branch
#Workflow - current flow is the workflow file which will be triggered
env:
  REPO_OWNER: arshrrevishnu
  REPO_NAME:  actionsDemo
  GITHUB_TOKEN: ${{secrets.TOKEN}}

on: #Events
  repository_dispatch: 
    types: [run_ping]


jobs: #Jobs
  build: #Job 1

    runs-on: macOs-latest # Runners

    steps: #Steps
      - uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3 #User name/repo name@release version
        with:
          java-version: '18.0.2+101'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build
