name: actionsDemo

#Events - When some something happens to the master branch
#Workflow - current flow is the workflow file which will be triggered
on: #Events
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs: #Jobs
  build: #Job 1

    runs-on: macOs-latest # Runners

    steps: #Steps
      - name: Checking out the code
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3 #User name/repo name@release version
        with:
          java-version: '18.0.2+101'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build
      - name: send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Mail from actionsDemo2
          to: shrrevishnu@gmail.com
          from: shrrevishnu@gmail.com
          body: Hi I am coming from ${{github.repository}}. The build was successful.

